### ISSUE TITLE
Excessive CPU usage in 6.1.2 on macOS

### ISSUE THREAD

**Issue by mehlkopf** [haiwen/seafile-client#1000]
Hi,

unfortunately, version 6.1.2 shows excessive CPU usage on multiple Macs I've tested it on, around 10-15 times what 6.1.1 needed on the same machines with the same configs, when the client is idle. macOS version I've experienced this problem with is 10.12.6.

Thank you!

Best,
Andreas

**Comment by freeplant** [comment]
Do you have information on which processor use more CPU? Seafile contains seaf-applet, seaf-daemon, ccnet three processors.

**Comment by mehlkopf** [comment]
Sorry - it's the app's process, daemon and ccnet are behaving more or less as usually. This is without an open window of Seafile, no sync in progress, it's just sitting in the menu bar.

**Comment by freeplant** [comment]
Do you have something unusual in applet.log?

**Comment by mehlkopf** [comment]
No, no logs except for usual starting/stopping actions.

**Comment by freeplant** [comment]
Can you send me a screenshot of the energy usage in Activity Monitor?

**Comment by mehlkopf** [comment]
Attached screenshots of both CPU and energy usage with 6.1.2. Average energy usage is of no value because I've switched back to 6.1.1 in the meantime.
<img width="789" alt="seafile client cpu usage" src="https://user-images.githubusercontent.com/13240642/32323402-3525142a-bfc8-11e7-939f-d871f2c0c941.png">
<img width="613" alt="seafile client energy usage" src="https://user-images.githubusercontent.com/13240642/32323403-35473eba-bfc8-11e7-9653-bcae64fe1549.png">

**Comment by lins05** [comment]
Fixed in https://github.com/haiwen/seafile-client/commit/a4ba081

**Comment by mehlkopf** [comment]
What kind of additional information do you need to fix that bug? Version 6.1.4 still uses CPU excessively, meaning that it is a complete mess to use on macOS. To be honest, I think this is such a serious issue usual testing before releasing any version of the Seafile Client should reveal that and no version should ever be released with such serious issues, let alone stay in there for 3 more versions …

**Comment by freeplant** [comment]
What is Seafile's CPU usage in your machine? In my Mac, it is about 1.7%.

**Comment by mehlkopf** [comment]
It's 2.5-3 % on my Mac, and that's TBH unacceptable on mobile machines: that's 3x my total idle load of all other processes (including VPN clients etc.) and 10x Dropbox's CPU usage - and it's 10x what the Seafile Client used in version 6.1.1, so it should IMHO be possible to examine the changes from 6.1.1 to 6.1.2 and get the CPU load to where it was before 6.1.2. Thank you!

**Comment by mehlkopf** [comment]
The issue is still not resolved and still has the "need-information" label - it would be nice to tell me what kind of information is still needed or remove the label to get this annoying (for every single (laptop) Mac user, even if they don't know it, but see decreased battery life!!) issue fixed … Thanks!

**Comment by mehlkopf** [comment]
All the same with version 6.1.5 - CPU usage of idle Seafile is higher than idle usage of all my VPN client and 12 apps combined ... Would be great to see it revert to the state of 6.1.1 when everything was fine (the good old times) - thank you …

**Comment by dakira** [comment]
I do not have this issue on a factory fresh Macbook Pro 13" with touch bar. I'll check our other company Macs, too. v6.1.8.

**Comment by mehlkopf** [comment]
Actually, the freshly (today?) released version 6.2.3 fixed the CPU usage problem! Thanks for the support, I am quite happy again!
